openapi: 3.0.0
info:
  description: This API provides event stats
  version: "1.0.0"
  title: Stats API
  contact:
    email: mchung71@my.bcit.ca

paths:
  /health:
    get:
      summary: check service health
      operationId: app.get_health
      responses:
        '200':
          description: Processing service is running
          content:
            application/json: 
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/health'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /stats:
    get: 
      summary: Gets the event stats
      operationId: app.get_stats
      description: Gets UFO sighting and cryptid processed statistics
      responses: 
        '200':
          description: Successfully returned a list of UFO sightings
          content:
            application/json: 
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/SightingStats'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    health: 
      required: 
        - audit
        - processing
        - receiver
        - storage
      properties:
        audit:
          type: string
          example: "running"
        processing:
          type: string
          example: "running"
        receiver:
          type: string
          example: "running"
        storage:
          type: string
          example: "running"
      type: object

    SightingStats:
      required:
        - num_ufo_sightings
        - curr_ufo_num
        - num_cryptid_sightings
        - curr_cryptid_num
      properties:
        num_ufo_sightings:
          type: integer
          example: 100
        curr_ufo_num:
          type: integer
          example: 5
        num_cryptid_sightings:
          type: integer
          example: 100
        curr_cryptid_num:
          type: integer
          example: 5
      type: object