openapi: 3.0.0
info:
  description: This API provides health checks
  version: "1.0.0"
  title: Health API
  contact:
    email: mchung71@my.bcit.ca

paths:
  /health:
    get:
      summary: check service health
      operationId: app.get_health
      parameters:
        - name: health
          in: query
          schema:
            type: integer
            example: 200
      responses:
        '200':
          description: Processing service is running
          content:
            application/json: 
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/health'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    health: 
      type: object
      required:
        - health
      properties:
        health:
          type: integer
          example: 200